import type { Metadata } from "next";
import { Noto_Sans } from "next/font/google";
import "./globals.css";

const noto = Noto_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Corsea",
  description: "Generated by create next app",
  authors: [{ name: "Michael Mathew", url: "https://cv-roan-seven.vercel.app", }],
  // viewport: { width: "device-width", initialScale: 1 }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={noto.className}>{children}</body>
    </html>
  );
}
